name: Building .NET Core Project
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ["8.0.x"]
    steps:
      - name: Checkout the Project
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v5.0.0
        with:
          dotnet-version: ${{matrix.dotnet-version}}

      - name: Restore Packages
        run: dotnet restore

      - name: Build Project
        run: dotnet build --configuration Release --no-restore

      - name: Publish
        run: dotnet publish -o ./published

      - name: Deploy to Azure App service
        uses: azure/webapps-deploy@v3
        with:
          app-name: EShopWebAppProd
          package: ./published
          publish-profile: ${{secrets.AZURE_WEBAPP_PUBLISH_PROFILE}}
      
